# -*- coding: utf-8 -*-
"""member8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDKtG9QGO_Jm7y9Jck7t-pk0ztwvZ-ky
"""

"""
MEMBER 8: Logging Module

Role: Save all transcriptions to files with timestamps.
Each session gets its own file with clear structure.
Handle Urdu text with UTF-8 encoding.
"""

import os
import datetime
import time


class LoggingModule:
    """
    Handles all logging functionality for the STT system.
    Creates timestamped log files and writes structured entries.
    """

    def __init__(self):
        """Initialize the logging module."""
        self.log_file = None
        self.current_log_file = None
        self.session_start_time = None
        self.line_count = 0

    def ensure_log_directory(self):
        """
        Creates logs folder if it doesn't exist.
        Handles permission errors gracefully.

        Returns:
            bool: True if directory exists/created, False on error
        """
        try:
            if not os.path.exists('logs'):
                os.makedirs('logs')
                print("📁 Created logs directory")
            return True
        except PermissionError:
            print("❌ ERROR: Permission denied. Cannot create logs folder.")
            return False
        except Exception as e:
            print(f"❌ ERROR: Could not create logs folder: {e}")
            return False

    def generate_filename(self):
        """
        Creates filename with pattern: transcript_YYYYMMDD_HHMMSS.txt

        Returns:
            str: Full path to log file
        """
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"transcript_{timestamp}.txt"
        return os.path.join('logs', filename)

    def start_session(self):
        """
        Starts a new logging session:
        - Creates logs folder if needed
        - Generates unique filename
        - Opens file with UTF-8 encoding
        - Writes session header

        Returns:
            bool: True if successful, False otherwise
        """
        # Ensure logs directory exists
        if not self.ensure_log_directory():
            return False

        # Generate filename
        self.current_log_file = self.generate_filename()
        self.session_start_time = time.time()

        try:
            # Open file with UTF-8 encoding (essential for Urdu)
            self.log_file = open(self.current_log_file, 'w', encoding='utf-8')

            # Write session header
            start_time_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            self.log_file.write("=" * 40 + "\n")
            self.log_file.write(f"Offline Urdu STT System - Session Log\n")
            self.log_file.write("=" * 40 + "\n")
            self.log_file.write(f"Session started: {start_time_str}\n")
            self.log_file.write("=" * 40 + "\n\n")
            self.log_file.flush()

            print(f"📝 Logging started: {self.current_log_file}")
            return True

        except Exception as e:
            print(f"❌ ERROR: Could not create log file: {e}")
            return False

    def log_transcription(self, timestamp, text):
        """
        Writes a transcription line to the log file.
        Called by Member 7 for each final sentence.

        Args:
            timestamp: Time string in HH:MM:SS format
            text: Transcribed Urdu text

        Returns:
            bool: True if successful, False otherwise
        """
        if self.log_file is None:
            print("⚠️ Warning: No active log file. Call start_session() first.")
            return False

        try:
            # Write line with timestamp
            self.log_file.write(f"[{timestamp}] {text}\n")
            self.log_file.flush()  # Ensure data is saved immediately
            self.line_count += 1
            return True
        except Exception as e:
            print(f"❌ ERROR: Failed to write to log file: {e}")
            return False

    def get_logger_function(self):
        """
        Returns the log_transcription function for Member 7.

        Returns:
            function: The log_transcription method
        """
        return self.log_transcription

    def end_session(self, duration, sentence_count):
        """
        Ends the current logging session:
        - Writes session footer with statistics
        - Closes the file
        - Returns log file path for display

        Args:
            duration: Session duration in seconds
            sentence_count: Total sentences in this session

        Returns:
            str: Path to the log file, or None on error
        """
        if self.log_file is None:
            print("⚠️ Warning: No active log session.")
            return None

        try:
            # Write session footer
            end_time_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            minutes = int(duration // 60)
            seconds = int(duration % 60)

            self.log_file.write("\n" + "-" * 40 + "\n")
            self.log_file.write(f"Session ended: {end_time_str}\n")
            self.log_file.write(f"Total sentences: {sentence_count}\n")
            self.log_file.write(f"Processing time: {minutes}m {seconds}s ({duration:.2f}s)\n")
            self.log_file.write(f"Lines logged: {self.line_count}\n")
            self.log_file.write("=" * 40 + "\n")

            # Close the file
            self.log_file.close()
            self.log_file = None

            print(f"✅ Log saved to: {self.current_log_file}")
            return self.current_log_file

        except Exception as e:
            print(f"❌ ERROR: Failed to end session properly: {e}")
            return None

    def get_current_log_file(self):
        """
        Returns the current log file path.

        Returns:
            str: Current log file path or None
        """
        return self.current_log_file

    def list_all_logs(self):
        """
        Returns a list of all log files in the logs folder.

        Returns:
            list: List of log filenames
        """
        if not os.path.exists('logs'):
            return []

        logs = [f for f in os.listdir('logs') if f.startswith('transcript_') and f.endswith('.txt')]
        return sorted(logs, reverse=True)  # Most recent first

    def read_log_file(self, filename):
        """
        Reads and returns the contents of a log file.

        Args:
            filename: Name of log file (with or without path)

        Returns:
            str: File contents or None on error
        """
        # Handle both full path and just filename
        if not os.path.dirname(filename):
            filepath = os.path.join('logs', filename)
        else:
            filepath = filename

        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                return f.read()
        except Exception as e:
            print(f"❌ ERROR: Could not read log file: {e}")
            return None

    def abort_session(self):
        """
        Aborts the current session without writing footer.
        Used when session ends unexpectedly.
        """
        if self.log_file:
            try:
                self.log_file.write("\n" + "=" * 40 + "\n")
                self.log_file.write("SESSION ABORTED\n")
                self.log_file.write("=" * 40 + "\n")
                self.log_file.close()
            except:
                pass
            finally:
                self.log_file = None

if __name__ == "__main__":
    print("=" * 60)
    print("TESTING MODULE 8: Logging Module")
    print("=" * 60)

    # Create logger instance
    logger = LoggingModule()

    # Test 1: Start session
    print("\n📋 Test 1: Starting session...")
    if logger.start_session():
        print("   ✅ Session started successfully")
    else:
        print("   ❌ Failed to start session")

    # Test 2: Log some transcriptions
    print("\n📋 Test 2: Logging transcriptions...")
    test_transcriptions = [
        ("14:35:22", "میں بازار جا رہا ہوں"),
        ("14:35:25", "آج موسم بہت اچھا ہے"),
        ("14:35:28", "کل ہم سکول جائیں گے"),
        ("14:35:32", "اسلام آباد پاکستان کا دارالحکومت ہے"),
    ]

    for timestamp, text in test_transcriptions:
        if logger.log_transcription(timestamp, text):
            print(f"   ✅ Logged: [{timestamp}] {text[:20]}...")
        else:
            print(f"   ❌ Failed to log: {text[:20]}...")
        time.sleep(0.1)  # Small delay for realistic timing

    # Test 3: End session
    print("\n📋 Test 3: Ending session...")
    log_path = logger.end_session(duration=125.5, sentence_count=4)
    if log_path:
        print(f"   ✅ Session ended, log saved to: {log_path}")
    else:
        print("   ❌ Failed to end session")

    # Test 4: List all logs
    print("\n📋 Test 4: Listing all log files...")
    all_logs = logger.list_all_logs()
    if all_logs:
        print(f"   Found {len(all_logs)} log files:")
        for i, log in enumerate(all_logs[:5]):  # Show first 5
            print(f"      {i+1}. {log}")
    else:
        print("   No log files found")

    # Test 5: Read the latest log
    print("\n📋 Test 5: Reading latest log file...")
    if all_logs:
        content = logger.read_log_file(all_logs[0])
        if content:
            print("   ✅ Successfully read log file")
            print("\n   First 5 lines of log:")
            lines = content.split('\n')
            for i, line in enumerate(lines[:5]):
                print(f"      {line}")

    # Test 6: Error handling test
    print("\n📋 Test 6: Testing error handling...")
    # Try to log without active session
    logger.log_file = None  # Simulate no active session
    result = logger.log_transcription("12:00:00", "Test")
    print(f"   Logging without session returns: {result} (should be False)")

    print("\n" + "=" * 60)
    print("✅ MODULE 8 TEST COMPLETE")
    print("=" * 60)

